/**
 * EMS.Gateway
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ContractType = 'Employment' | 'Commission' | 'SpecificTask';

export const ContractType = {
    Employment: 'Employment' as ContractType,
    Commission: 'Commission' as ContractType,
    SpecificTask: 'SpecificTask' as ContractType
};

