/**
 * EMS.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ContactType = 'Email' | 'Telephone' | 'Fax' | 'Skype' | 'Other';

export const ContactType = {
    Email: 'Email' as ContactType,
    Telephone: 'Telephone' as ContactType,
    Fax: 'Fax' as ContactType,
    Skype: 'Skype' as ContactType,
    Other: 'Other' as ContactType
};

