/**
 * EMS.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ContractPrivacy = 'Private' | 'Company';

export const ContractPrivacy = {
    Private: 'Private' as ContractPrivacy,
    Company: 'Company' as ContractPrivacy
};

