/**
 * EMS.Gateway
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SalaryType } from './salaryType';
import { ContractType } from './contractType';


export interface ContractModel { 
    id: string;
    employmentDate: string;
    conclusionDate: string;
    positionItemId?: string | null;
    positionItemName?: string | null;
    workplaceItemId?: string | null;
    workplaceItemName?: string | null;
    occupationCodeItemId?: string | null;
    occupationCodeName?: string | null;
    startDate: string;
    terminationDate?: string | null;
    fteNumerator: number;
    fteDenominator: number;
    salary: number;
    salaryType: SalaryType;
    contractType: ContractType;
}
export namespace ContractModel {
}


