/**
 * EMS.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Training } from './training';
import { Employee } from './employee';
import { MedicalExamination } from './medicalExamination';
import { Contract } from './contract';


export interface CreateEmployeeModel { 
    employee: Employee;
    contract?: Contract;
    medicalExaminations?: Array<MedicalExamination> | null;
    trainings?: Array<Training> | null;
}

