/**
 * EMS.Gateway
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Training } from './training';
import { Employee } from './employee';
import { MedicalExamination } from './medicalExamination';
import { Contract } from './contract';


export interface CreateEmployeeModel { 
    employee: Employee;
    contract?: Contract | null;
    medicalExaminations?: Array<MedicalExamination> | null;
    trainings?: Array<Training> | null;
    imageBase64?: string | null;
}

