/**
 * EMS.Gateway
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SchoolType } from './schoolType';


export interface EducationModel { 
    id: string;
    schoolName: string;
    type: SchoolType;
    start: string;
    end: string;
    degree?: string | null;
    occupation?: string | null;
}
export namespace EducationModel {
}


