/**
 * EMS.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EmployeeShortInfoModel { 
    id: string;
    name: string;
    surname: string;
    pesel?: string | null;
    employmentDate: string;
    salary: number;
    salaryType: string;
    contractType: string;
    fteDenominator: number;
    fteNumerator: number;
}

