/**
 * EMS.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SalaryType } from './salaryType';
import { ContractType } from './contractType';


export interface EmployeeShortInfoModel { 
    id: string;
    imageName?: string | null;
    name: string;
    surname: string;
    pesel?: string | null;
    contractType?: ContractType | null;
    employmentDate?: string | null;
    terminationDate?: string | null;
    salary?: number | null;
    salaryType?: SalaryType | null;
    fteDenominator?: number | null;
    fteNumerator?: number | null;
}
export namespace EmployeeShortInfoModel {
}


