/**
 * EMS.Gateway
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Address } from './address';
import { PaymentMethod } from './paymentMethod';
import { Gender } from './gender';


export interface Employee { 
    name: string;
    surname: string;
    pesel?: string | null;
    nip?: string | null;
    birthdate?: string | null;
    gender?: Gender | null;
    address?: Address | null;
    phoneNumber?: string | null;
    email?: string | null;
    paymentMethod?: PaymentMethod | null;
}
export namespace Employee {
}


