/**
 * EMS.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Address } from './address';
import { PaymentMethod } from './paymentMethod';
import { Gender } from './gender';


export interface EmployeeModel { 
    id: string;
    name: string;
    surname: string;
    pesel?: string | null;
    nip?: string | null;
    birthdate?: string | null;
    gender: Gender;
    address: Address;
    phoneNumber?: string | null;
    email?: string | null;
    paymentMethod: PaymentMethod;
}
export namespace EmployeeModel {
}


