/**
 * EMS.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EmployeeShortInfoModel { 
    id?: string;
    name?: string | null;
    surname?: string | null;
    pesel?: string | null;
    employmentDate?: string;
    salary?: number;
    salaryType?: string | null;
    contractType?: string | null;
    fteDenominator?: number;
    fteNumerator?: number;
}

