/**
 * EMS.Gateway
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Gender = 'Male' | 'Female';

export const Gender = {
    Male: 'Male' as Gender,
    Female: 'Female' as Gender
};

