/**
 * EMS.Gateway
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MedicalExaminationModel { 
    id: string;
    employeeId: string;
    medicalExamItemId: string;
    medicalExamItem: string;
    executionDate: string;
    expirationDate?: string | null;
}

