/**
 * EMS.Gateway
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface QualificationModel { 
    id: string;
    employeeId: string;
    qualificationItemId: string;
    qualificationItem: string;
    expirationDate?: string | null;
}

