/**
 * EMS.Gateway
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type RecordStatus = 'Actual' | 'Ending' | 'Ended';

export const RecordStatus = {
    Actual: 'Actual' as RecordStatus,
    Ending: 'Ending' as RecordStatus,
    Ended: 'Ended' as RecordStatus
};

