/**
 * EMS.Gateway
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type SchoolType = 'Type1' | 'Type2';

export const SchoolType = {
    Type1: 'Type1' as SchoolType,
    Type2: 'Type2' as SchoolType
};

