/**
 * EMS.Gateway
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TrainingModel { 
    id: string;
    employeeId: string;
    trainingItemId: string;
    trainingItem: string;
    executionDate: string;
    expirationDate?: string | null;
}

