export * from './contract.service';
import { ContractService } from './contract.service';
export * from './dashboard.service';
import { DashboardService } from './dashboard.service';
export * from './education.service';
import { EducationService } from './education.service';
export * from './employees.service';
import { EmployeesService } from './employees.service';
export * from './medicalExaminationDict.service';
import { MedicalExaminationDictService } from './medicalExaminationDict.service';
export * from './medicalExaminations.service';
import { MedicalExaminationsService } from './medicalExaminations.service';
export * from './occupationDict.service';
import { OccupationDictService } from './occupationDict.service';
export * from './positionDict.service';
import { PositionDictService } from './positionDict.service';
export * from './qualificationDict.service';
import { QualificationDictService } from './qualificationDict.service';
export * from './qualifications.service';
import { QualificationsService } from './qualifications.service';
export * from './trainingDict.service';
import { TrainingDictService } from './trainingDict.service';
export * from './trainings.service';
import { TrainingsService } from './trainings.service';
export * from './workplaceDict.service';
import { WorkplaceDictService } from './workplaceDict.service';
export const APIS = [ContractService, DashboardService, EducationService, EmployeesService, MedicalExaminationDictService, MedicalExaminationsService, OccupationDictService, PositionDictService, QualificationDictService, QualificationsService, TrainingDictService, TrainingsService, WorkplaceDictService];
